printf("setting variables...\n");
timestampMs = EEGdelta(:,1); 
poorSignal = EEGdelta(:,2); 
eegRawValue = EEGdelta(:,3); 
eegRawValueVolts = EEGdelta(:,4); 
attention = EEGdelta(:,5); 
meditation = EEGdelta(:,6); 
blinkStrength = EEGdelta(:,7); 
delta = EEGdelta(:,8); 
theta = EEGdelta(:,9); 
alphaLow = EEGdelta(:,10); 
alphaHigh = EEGdelta(:,11); 
betaLow = EEGdelta(:,12); 
betaHigh = EEGdelta(:,13); 
gammaLow = EEGdelta(:,14); 
gammaMid = EEGdelta(:,15); 
